name: Building doxygen docs

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build_and_publish:
    runs-on: ubuntu-20.04
    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get update && sudo apt-get install g++ extra-cmake-modules qttools5-dev qttools5-dev-tools libsdl2-dev libxi-dev libxtst-dev libx11-dev itstool gettext cmake doxygen graphviz

      # Runs a set of commands using the runners shell
      - name: Build docs
        run: |
          ls
          pwd
          cd ..
          git clone https://github.com/AntiMicroX/antimicrox.git
          mkdir antimicrox/build
          cd antimicrox/build
          cmake .. -DBUILD_DOCS=ON
          cmake --build ./ --target doxygen_docs
          cd /home/runner/work/doxygen/doxygen

      - name: List files
        run: |
          ls
          pwd
          cd ../antimicrox/docs/html
          ls

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-page
          build_dir: ../antimicrox/docs/html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
